Fix stacktrace format for rollbar
chatchamp/winston-rollbar pull request #5
Opened 2023-06-12 09:26 UTC by catnstein

2023-06-12 13:36 UTC, dominik1001 requested changes
see comment

2023-06-12 13:36 UTC, dominik1001 commented on lib/rollbar_transport.js
> +      return logMethod.apply(this.rollbar, [message, info, new Error(info.stack), cb]);
Creating a new error here seems wrong to me

2023-06-13 16:49 UTC, thiagosf commented on lib/rollbar_transport.js
> +    }
Great function 👏 ! I'd change to put the return in one line, like that:
```js
if (info.message instanceof Error) return info.message;
```

2023-06-13 16:50 UTC, thiagosf commented on test/rollbar_transport.spec.js
> +});
Strong tests 💪

2023-06-14 13:25 UTC, dominik1001 requested changes
I am through. 😮‍💨

1. The API of winston is not very clear and developer-friendly IMO. There is a lot of discussion about this topic.
https://github.com/winstonjs/winston/issues/1338

2. When you use logger.error(err) the err becomes the message, so in general the original implementation is correct.

3. However, to properly log errors rollbar expects the errors to be passed to `rollbar.error(err)`. This was not happening due to two reasons:

A) We use the colorizer before passing data to rollbar. That is why this `this.rollbar[rollbarLevel]` is not working because rollbarLevel is not `error` but `somethingerrorsomething`.

B) We format this error before passing it to rollbar

`util.format(info.message, ...(info.splat || []));`

We should not do that for errors.

So if we fix A and B everything should work.

I don't really like line 34 because it suggests that we can only log errors to rollbar which is not true. And I think even though the API sucks the caller should always make sure that the error object is properly passed as the message.

2023-06-16 13:20 UTC, catnstein commented
> I am through. 😮‍💨
> 
> 1. The API of winston is not very clear and developer-friendly IMO. There is a lot of discussion about this topic.
>    [[3.0.0] Error object is not parsed or printed winstonjs/winston#1338](https://github.com/winstonjs/winston/issues/1338)
> 2. When you use `logger.error(err)` the `err` becomes the `message`, so in general the original implementation is correct.
> 3. However, to properly log errors rollbar expects the errors to be passed to `rollbar.error(err)`. This was not happening due to two reasons:
> 
> A) We use the colorizer before passing data to rollbar. That is why this `this.rollbar[rollbarLevel]` is not working because rollbarLevel is not `error` but `somethingerrorsomething`. The colorizer should only be used for console and papertrail.
> 
> B) We format this error before passing it to rollbar
> 
> `util.format(info.message, ...(info.splat || []));`
> 
> We should not do that for errors.
> 
> So if we fix A and B everything should work.
> 
> I don't really like line 34 because it suggests that we can only log errors to rollbar which is not true. And I think even though the API sucks the caller should always make sure that the error object is properly passed as the message.

@dominik1001 I've reimplemented the log function, everything should be logged correctly now. Thanks so much for the help 🙏

2023-06-19 08:28 UTC, dominik1001 requested changes
This looks quite good. Two last small things.

2023-06-19 08:28 UTC, dominik1001 commented on lib/rollbar_transport.js
> -    process.nextTick(() => {
We're changing a lot of code where I guess it's unclear why it was there in the first place. The git history doesn't tell a good story, and without unit tests it's hard to say why that has been there in the first place, so I think it's ok.

2023-06-19 08:28 UTC, dominik1001 commented on lib/rollbar_transport.js
> +    if (level === 'error') {
Two things I'd still add however.
1. There is no fallback, when the level is something else. I'd leave that to `rollbar.log` or `ino`
2. `warning` used to work as `warn` before, we could still keep that

2023-06-19 09:05 UTC, dominik1001 approved these changes

2023-06-19 09:37 UTC, catnstein commented on lib/rollbar_transport.js
> +    if (level === 'error') {
added fallback to `info` 👍

2023-06-19 09:38 UTC, merged